### ISSUE TITLE
Fail to find the article title

### ISSUE THREAD

**Issue by MinhDinh-4869** [thenaterhood/python-autocite#10]
For some urls, the title in the citation is returned as "". This issue occurs when I use the `--from-file` option only. I have found out that it due to the list of urls in file, when reading them, except for the last one, the url will have the breakline character '\n' at the end and when we use that url, the wrong page could be requested.

I also find out an issue with the `--to-text` option, that it will fail to write the citation to file the citation have the unicode character.

Here is a patch I made, if you guys encounter the same issue, you can apply it. Thanks
[0001-Remove-the-breakline-character-at-the-end-of-the-url.patch](https://github.com/user-attachments/files/17268539/0001-Remove-the-breakline-character-at-the-end-of-the-url.patch)

**Comment by thenaterhood** [comment]
Thanks for the fix! I've applied your patch and it's merged into the master branch
