### ISSUE TITLE
Bibtex Style Citation Request

### ISSUE THREAD

**Issue by zzj0402** [thenaterhood/python-autocite#6]
I am using the LaTeX package to compile papers. BibTeX is a handy citation tool to use.

For this webpage
`https://www.cisco.com/c/en/us/products/security/what-is-cybersecurity.html`
I would have the following:
```
@misc{cisco_2020, title={What Is Cybersecurity?}, url={https://www.cisco.com/c/en/us/products/security/what-is-cybersecurity.html}, journal={Cisco}, publisher={Cisco}, author={Cisco}, year={2020}, month={Nov}}
```

**Comment by thenaterhood** [comment]
Check out v0.0.4. It can probably use some improvements because I'm not intimately familiar with the format, but the basics should be there.
