### ISSUE TITLE
Having Trouble Running setup.py "no commands supplied" error

### ISSUE THREAD

**Issue by kch0p** [thenaterhood/python-autocite#7]
Hey Nate, super excited to use this tool. I'm trying to run the `setup.py` file, but it keeps producing a 'no commands supplied error' that prevents it from getting set up. Am I missing something here? Thanks so much. 

<img width="1159" alt="Screen Shot 2022-09-09 at 12 37 45 PM" src="https://user-images.githubusercontent.com/89766547/189430354-6323d61a-1d14-4188-b4a4-ab85abeed982.png">

**Comment by thenaterhood** [comment]
`python setup.py install` should install it if you have setuptools installed, or `pip install -e .` if you're using pip.
